version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"
    ports:
      - 5432:5432
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
